ARG BASE_IMAGE="quay.io/aipcc/base-images/cpu:3.4"

FROM ${BASE_IMAGE}

COPY pipelines/training/automl/autogluon_tabular_training_pipeline/requirements.txt \
     pipelines/training/automl/autogluon_tabular_training_pipeline/requirements-pypi.txt \
     /tmp/

## Ensure build isolation
RUN pip install --no-cache-dir -r /tmp/requirements.txt
RUN pip install --index-url https://pypi.org/simple --no-cache-dir -r /tmp/requirements-pypi.txt

## Install kfp-components from local source
RUN mkdir /tmp/kfp-src
COPY . /tmp/kfp-src/
RUN pip install --no-cache-dir --no-build-isolation --no-deps /tmp/kfp-src/ && \
    rm -rf /tmp/kfp-src/
